//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerencia_Proyectos_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajasRecepcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajasRecepcion()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
        }
    
        public int IdCaja { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<int> IdOrden { get; set; }
        public Nullable<int> IDProd { get; set; }
        public string EstadoPedido { get; set; }
        public string TipoProd { get; set; }
        public string DescProd { get; set; }
        public decimal PrecioProd { get; set; }
        public int CantProd { get; set; }
    
        public virtual OrdenPedidos OrdenPedidos { get; set; }
        public virtual MenuProductos MenuProductos { get; set; }
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
    }
}
