//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerencia_Proyectos_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura
    {
        public int id_detalleFactura { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> Id_Orden { get; set; }
        public Nullable<int> Id_Mesa { get; set; }
        public Nullable<int> Id_Caja { get; set; }
        public Nullable<int> cantidad_articulo { get; set; }
    
        public virtual CajasRecepcion CajasRecepcion { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Mesas Mesas { get; set; }
        public virtual OrdenPedidos OrdenPedidos { get; set; }
    }
}
