//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerencia_Proyectos_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gp_CafeteriaEntities : DbContext
    {
        public gp_CafeteriaEntities()
            : base("name=gp_CafeteriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CajasRecepcion> CajasRecepcion { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<MenuProductos> MenuProductos { get; set; }
        public virtual DbSet<Mesas> Mesas { get; set; }
        public virtual DbSet<OrdenPedidos> OrdenPedidos { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
    }
}
