//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerencia_Proyectos_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenPedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenPedidos()
        {
            this.CajasRecepcion = new HashSet<CajasRecepcion>();
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int IdOrden { get; set; }
        public string CodProd { get; set; }
        public Nullable<int> IDProd { get; set; }
        public Nullable<int> IdMesa { get; set; }
        public string Descrpción { get; set; }
        public int Cantidad { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CajasRecepcion> CajasRecepcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual MenuProductos MenuProductos { get; set; }
        public virtual Mesas Mesas { get; set; }
    }
}
